# Generated by Django 3.0.4 on 2020-03-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option1', models.CharField(max_length=20)),
                ('option1_votes', models.IntegerField(default=0)),
                ('option2', models.CharField(max_length=20)),
                ('option2_votes', models.IntegerField(default=0)),
                ('option3', models.CharField(max_length=20)),
                ('option3_votes', models.IntegerField(default=0)),
            ],
        ),
    ]
